### ISSUE TITLE
Update existing issues in the organization

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/.github#10]
## Overview

To promote consistency and understanding of the project's goals, we want to implement some agile processes. The starting point is to build our backlog with issues that contain all the information required to solve them.

We aim to rewrite open issues with the current template and tweak the proposed template as the needs arise. 

## Acceptance criteria

- Open issues follow the proposed templates
- The templates are reviewed and adapted until approved by the team

## Tasks

- [ ] [App Telos Native](https://github.com/telosnetwork/app-telos-native/issues): @Viterbo 
- [ ] [Teloscan](https://github.com/telosnetwork/teloscan/issues): @EJSG 
- [ ] [OBE](https://github.com/telosnetwork/open-block-explorer/issues): @karynemayer 
- [ ] [Wallet](https://github.com/telosnetwork/telos-wallet/issues): @karynemayer 
- [ ] [EVM Docker](https://github.com/telosnetwork/telos-evm-docker/issues): @guilledk 
- [ ] [Teloscan Indexer](https://github.com/telosnetwork/teloscan-indexer/issues): ❓
- [ ] [Hyperion EVM Plugin](https://github.com/telosnetwork/hyperion-telos-evm-plugin/issues): ❓
- [ ] [Haproxy Manager](https://github.com/telosnetwork/haproxy-manager/issues): @poplexity 
- [ ] [Research](https://github.com/telosnetwork/telos-research/issues): Amir
- [ ] [Telos Token Bridge](https://github.com/telosnetwork/telos-token-bridge/issues): @tomtomcrypto
