### ISSUE TITLE
Update Branding 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/.github#13]
**Tasks**
- [ ] Logo (Org)
- [ ] Description Logo (Org)
- [ ] Social Media Links (Org)
- [ ] https://github.com/telosnetwork/token-list/issues/64
- [ ] https://github.com/telosnetwork/teloscan/issues/484
- [ ] https://github.com/telosnetwork/telos-wallet/issues/678
- [ ] https://github.com/telosnetwork/open-block-explorer/issues/808
- [ ] https://github.com/telosnetwork/app-telos-native/issues/321

**Comment by pmjanus** [comment]
Awaiting design for telos zero on wallet
